---
# handlers file for elk

- name: start and enable elasticsearch
  service:
    name: elasticsearch
    state: started
    enabled: yes
- name: start and enable kibana
  service: 
    name: kibana
    state: started
    enabled: yes
- name: start and enable nginx
  service: 
    name: nginx
    state: started
    enabled: yes
- name: start and enable logstash
  service:
    name: logstash
    state: started
    enabled: yes
- name: start and enable filebeat
  service:
    name: filebeat
    state: started
    enabled: yes
- name: start and enable metricbeat
  service:
    name: metricbeat
    state: started
    eanble: yes
...
